apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-backend
  template:
    metadata:
      labels:
        app: ticketing-backend
    spec:
      containers:
        - name: backend
          image: mitaakash/ticketing-backend
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-backend
  namespace: ticketing-project
spec:
  type: ClusterIP
  selector:
    app: ticketing-backend
  ports:
    - protocol: TCP
      port: 5000        # service port
      targetPort: 5000  # container port

